name: road_helperr
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  pin_code_fields: ^8.0.1
  video_player: ^2.7.2
  google_fonts: ^6.2.1
  gradient_slide_to_act: ^0.0.2
  shared_preferences: ^2.3.3
  image_picker: ^0.8.4+3
  geolocator: ^10.1.0
  geocoding: ^2.1.0 # تحديث
  google_maps_flutter: ^2.5.0
  http: ^1.1.0
  connectivity_plus: ^5.0.2
  permission_handler: ^11.0.0 # تحديث
  location: ^5.0.0 # تحديث
  flutter_polyline_points: ^2.0.0 # تحديث
  flutter_launcher_icons: ^0.9.2
  provider: ^6.1.4
  uuid: ^3.0.7
  intl: ^0.19.0
  flutter_gemini: ^3.0.0
  flutter_markdown: ^0.7.7
  firebase_core: ^2.24.2
  flutter_local_notifications: ^16.3.0
  package_info_plus: ^4.2.0
  path_provider: ^2.1.2
  in_app_update: ^4.2.2
  url_launcher: ^6.1.5
  firebase_messaging: ^14.7.10
  google_sign_in: ^6.2.1
  firebase_auth: ^4.15.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/
    - assets/videos/1.mp4
    - assets/videos/2.mp4
    - assets/videos/3.mp4
    - assets/map_style.json

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
